### ISSUE TITLE
Setup CI mingw

### ISSUE THREAD

**Issue by inkydragon** [libui-ng/libui-ng#1]
Then we can accept people's pr.

- [x] win - msvc
- [ ] win - mingw
- [x] ubuntu - gcc
- [x] macOS - clang

**Comment by cody271** [comment]
@inkydragon Agreed. We can't actually merge anything until CI is back online.

We'll have to port the AppVeyor and Azure Pipelines YAML configs to GitHub Actions though. Needs meson on all threes platforms, including Windows.

If you have CI experience with GitHub Actions, PR is welcome!

**Comment by cody271** [comment]
That was fast. Our CI status badge is now passing green!

@inkydragon do we still need mingw support before moving forward?

**Comment by inkydragon** [comment]
I think we can now move on.

Adding mingw to CI is great, but it shouldn't be a blocker that stops us from moving forward.
I'll keep trying to add a CI for mingw, and if there's no progress, then let's keep this issue open.

**Comment by cody271** [comment]
Sounds good, renaming this issue then and keeping it open for mingw support. Thanks @inkydragon!
