### ISSUE TITLE
Add system tray support by incorporating code like this?

### ISSUE THREAD

**Issue by adamierymenko** [libui-ng/libui-ng#105]
There are a number of cross-platform system tray app wrappers that work well. Here is one that we use:

https://github.com/zserge/tray

We have a fork with some modifications here:

https://github.com/zerotier/DesktopUI/tree/master/tray

It would be cool to integrate this functionality into libUI. Don't have time at the moment though. Given that the above code works it could *almost* be cut and pasted.

**Comment by cody271** [comment]
See https://github.com/libui-ng/libui-ng/issues/28
