### ISSUE TITLE
Multi-line labels result in REALLY wide windows on Windows.

### ISSUE THREAD

**Issue by adamierymenko** [libui-ng/libui-ng#106]
If you put a multi-line string into a label, this results in a REALLY wide window on MS Windows. I think it's calculating the string length of the entire string without taking into account carriage returns and sizing the window as if it's one big long line. Correct behavior would be to tokenize the string by CR/LF and take the maximum width to find the width of the label.

The macOS code seems to do the right thing already. Don't know about Linux.

Current workaround is to use a multi-line read-only text entry but this sort of doesn't look right due to control styling.

**Comment by cody271** [comment]
> Current workaround is to use a multi-line read-only text entry but this sort of doesn't look right due to control styling.

Screenshots always helpful: ideally of both the misbehaving label, and your read only entry workaround attempt if possible.

**Comment by rubyFeedback** [comment]
I guess it may help either way to add a screenshot, perhaps a simple sample code where we can compare between all three platforms; and then see how much the fix proposed above would change that.

**Comment by cody271** [comment]
Fixed in #112.
