### ISSUE TITLE
darwin: Creation of some controls within a second window causes a crash.

### ISSUE THREAD

**Issue by szanni** [libui-ng/libui-ng#157]
When creating certain controls within a second window through a user callback, the application crashes.

Here an example, or you can play around with the modified `hello-world` on this [branch](https://github.com/szanni/libui-ng/tree/darwin-uiNew-crash-on-user-callback).

```
#include <stdio.h>
#include <ui.h>

int onClosing(uiWindow *w, void *data)
{
	uiQuit();
	return 1;
}

int onClosingSub(uiWindow *w, void *data)
{
	return 1;
}

void buttonComboboxWindowOnClicked(uiButton *b, void *data)
{
	uiWindow *w;
	uiCombobox *child;
	w = uiNewWindow("Combobox", 300, 30, 0);
	uiWindowOnClosing(w, onClosingSub, NULL);
	child = uiNewCombobox();
	uiWindowSetChild(w, uiControl(child));
	uiControlShow(uiControl(w));
}

int main(void)
{
	uiInitOptions o = {0};
	const char *err;
	uiWindow *w;
	uiButton *b;

	err = uiInit(&o);
	if (err != NULL) {
		fprintf(stderr, "Error initializing libui-ng: %s\n", err);
		uiFreeInitError(err);
		return 1;
	}

	// Create a new window
	w = uiNewWindow("Hello World!", 300, 30, 0);
	uiWindowOnClosing(w, onClosing, NULL);

	b = uiNewButton("Combobox");
	uiButtonOnClicked(b, buttonComboboxWindowOnClicked, NULL);
	uiWindowSetChild(w, uiControl(b));

	/* Interestingly enough this works AND prevents the crash from happening
	 * when triggering the creating through the callback later on. */
	//buttonComboboxWindowOnClicked(uiButton *b, void *data)

	uiControlShow(uiControl(w));
	uiMain();
	uiUninit();
	return 0;
}
```
Crash log:

```
2022-12-04 00:29:41.337 hello-world[10896:501236] [libui] ../darwin/map.m:25:uiprivMapDestroy() POSSIBLE IMPLEMENTATION BUG; CONTACT ANDLABS:
attempt to destroy map with items inside
zsh: illegal hardware instruction  ./build/meson-out/hello-world
```

Controls I tested that exhibit that behavior:

- uiCombobox [showcase](https://github.com/szanni/libui-ng/tree/darwin-uiNew-crash-on-user-callback)
- uiSlider [showcase](https://github.com/szanni/libui-ng/tree/darwin-uiNewSlider-crash-on-user-callback)

Probably many more? Code that does weird things with delegates and `uiprivMap` internally? ~~Interestingly enough `uiButton` seems to be fine, although it uses `uiprivMap` for the delegates.~~

**Comment by szanni** [comment]
While triggered in a slightly different way, I stumbled across another way of crashing applications while working on a new control. This breaks uiButton, which, for whatever reason, is not affected by the first code path:

-  uiButton [showcase in qa > uiSplit](https://github.com/szanni/libui-ng/tree/darwin-uiButton-crash-on-user-callback)

This just reinforces my initial assessment: the weird singleton delegates must go.

**Comment by e1732a364fed** [comment]
I get another issue with the same crash information. Maybe related : #160

**Comment by szanni** [comment]
> I get another issue with the same crash information. Maybe related : #160

Guess you were quicker. Yes definitely the same issue from what I can tell! I'll fix `uiWindow` next and mark you in the PR so you can check if that fixes things. Thanks for reporting!
