### ISSUE TITLE
darwin: Remove singleton delegates and associated global state

### ISSUE THREAD

**Issue by szanni** [libui-ng/libui-ng#165]
This has been causing a lot of problems, both in C code #157 and #133, and in bindings #160.

IMO this needs to be resolved as soon as possible.

| control | possible fix | done |
|-|-|-|
| uiButton |#154 | |
| uiCheckbox | #166| |
| uiCombobox |#159 | |
|uiDatetimepicker | #168| |
|uiEditableCombobox|#167 | |
|uiEntry|#175 | |
|uiMenu |#172 | |
|uiSlider |#158 | |
|uiWindow |#162 | |

**Comment by szanni** [comment]
Fix suggestions are up for all affected controls.

**Comment by Frityet** [comment]
What problems are present as a result of the singletons?
