### ISSUE TITLE
uiNewMenu() fails when called a second time after uiUninit() and uiInit()

### ISSUE THREAD

**Issue by szanni** [libui-ng/libui-ng#169]
Similar to #118, another `uiUninit()` followed by `uiInit()` problem: Any application creating a menu and hence possibly calling `uiNewMenu()` after a reset (`uiUninit(); uiInit();`) will refuse to work the second time around.

You can check it out by running `meson test` on [this branch](https://github.com/szanni/libui-ng/tree/cmocka-menu)

Does anyone know why the menu needs to be finalized in the first place? Why can we not modify the menu after creating the first window? Is this related to a limitation of one of the underlying platforms or just a library quirk?

**Comment by cody271** [comment]
> Is this related to a limitation of one of the underlying platforms or just a library quirk?

Yes was related to Darwin's rather strict concept of a "menu" initially. Probably no longer needed now tho.

**Comment by szanni** [comment]
> > Is this related to a limitation of one of the underlying platforms or just a library quirk?
> 
> Yes was related to Darwin's rather strict concept of a "menu" initially. Probably no longer needed now tho.

Hm, interesting, yes, that is what I thought initially too, as all windows _seem?_ to share the same menu. But Darwin even supports deletions and I could not find anything in the docs saying you can not modify menus after window creation. Maybe I missed something?
The other thing that came to mind is win32, as certain flags need to be set upon creation for some controls and the docs are not reliable.

**Comment by szanni** [comment]
Fixed in #176
