### ISSUE TITLE
API string ownership clarification

### ISSUE THREAD

**Issue by bcampbell** [libui-ng/libui-ng#191]
From the tooltip api issue:
```c
/**
 * Sets the control tooltip.
 *
 * @param c uiControl instance.
 * @param tooltip Control tooltip.\n
 *             A valid, `NULL` terminated UTF-8 string.\n
 *             Data is owned by the caller.
 * @note Setting `NULL` resets the tooltip to the default value.
 * @memberof uiControl
 */
_UI_EXTERN void uiControlSetTooltip(uiControl *c, const char *tooltip);
```

_Originally posted by @cody271 in https://github.com/libui-ng/libui-ng/issues/188#issuecomment-1496781878_

My reading of that `uiControlSetTooltip()` doc comment is that the caller needs to ensure that the string pointed to by `tooltip` exists for the lifetime of the control, right?

I wanted to check that this was the same convention used elsewhere in libui. I picked uiButton as a random example:
And sure enough, `uiSetButtonText()` uses the same wording: "Data is owned by the caller".
But `uiButtonText()` says of the returned sting: "Data is owned by the caller, make sure to call `uiFreeText()`".

That seems rather... asymmetrical to me.
Is this really the general convention or am I just misreading the "Data is owned by the caller." comment?
- Set functions just stash a pointer without copying the string (and rely on the caller to ensure the string stays valid!)
- Get functions return a copy which must be freed by the caller

**Comment by bcampbell** [comment]
The more I think about it, the more I think I'm just misreading the comment. The API _must_ be taking a copy of the passed-in string.
Peeking through the code, the GTK and win32 `uiButton` implementations leave the string-copy policy up to those APIs.
And, while [`gtk_button_set_label()`](https://developer-old.gnome.org/gtk3/stable/GtkButton.html#gtk-button-set-label) and [`SetWindowTextW()`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowtextw) don't say so explicitly, I can't imagine that they _don't_ take a copy. Anything else would be madness.

So. Would anyone be open to a patch to change the wording on those comments in `ui.h`?
Out with: "Data is owned by the caller."
In with "The control will make it's own copy of the string." (or something less unwieldly...)

**Comment by szanni** [comment]
Yeah, my phrasing may have been a little confusing here.
`Data is owned by the caller.` meaning it is not transferred and ownership and memory management stays with the caller. Or as you say  `The control will make a copy.`.
This is essentially the GTK phrasing: `The data is owned by the caller of the function.` [source](https://docs.gtk.org/gtk3/method.Window.set_title.html)

Not terribly happy with that either. Open to suggestions.
Maybe `Data is copied internally. Ownership is not transferred.`?

**Comment by szanni** [comment]
Maybe something like:
`No data ownership transfer. The receiver will make a copy.`?

In general pretty much all `ui` methods will make a copy, there are some exceptions though around `uiAttributedString` (#126) and something around `uiTable` in conjunction with images if I remember correctly.

**Comment by nptr** [comment]
I was also confused by the description and fully support this issue.
Rewriting to what szanni proposed clarifies the situation a lot. I like `Data is copied internally. Ownership is not transferred.` best.

There is also another option: Don't mention ownership unless it changes or unless it isn't obvious anymore that it doesn't change.

**Comment by bcampbell** [comment]
OK, first-pass pull request #195
