### ISSUE TITLE
Combobox dropdown on windows shows no options

### ISSUE THREAD

**Issue by desttinghim** [libui-ng/libui-ng#203]
At first I thought this was an issue with Wine. However, I did some tests with an actual windows computer and a windows vm and I got the same result. Combobox list items are not visible due to the weird way windows handles comboboxes. A comment in `windows/combobox.cpp` links to [this article](https://web.archive.org/web/20140425003632/http://blogs.msdn.com/b/oldnewthing/archive/2006/03/10/548537.aspx) (it's bitrotted, so I swapped it with an internet archive link) and claims libui doesn't need to worry about the height of comboboxes. I don't know if this is a regression or if it's always been a bug.

**Comment by cody271** [comment]
Are you on the latest? Fix for this was merged recently: https://github.com/libui-ng/libui-ng/pull/197

**Comment by desttinghim** [comment]
I'm on the latest. Here's a minimal example reproducing the issue: 
```c
#include <stdio.h>
#include <ui.h>

int onClosing(uiWindow *w, void *data)
{
	uiQuit();
	return 1;
}

int main(void)
{
	uiInitOptions o = {0};
	const char *err;
	uiWindow *w;
	uiBox *vbox;
	uiCombobox *cbox;

	err = uiInit(&o);
	if (err != NULL) {
		fprintf(stderr, "Error initializing libui-ng: %s\n", err);
		uiFreeInitError(err);
		return 1;
	}

	// Create a new window
	w = uiNewWindow("Hello World!", 300, 30, 0);
	uiWindowOnClosing(w, onClosing, NULL);

	vbox = uiNewVerticalBox();
	uiWindowSetChild(w, uiControl(vbox));
	uiBoxSetPadded(vbox, 1);

	cbox = uiNewCombobox();
	uiComboboxAppend(cbox, "Combobox Item 1");
	uiComboboxAppend(cbox, "Combobox Item 2");
	uiComboboxAppend(cbox, "Combobox Item 3");
	uiBoxAppend(vbox, uiControl(cbox), 0);

	uiControlShow(uiControl(w));
	uiMain();
	uiUninit();
	return 0;
}
```
Without the box layout the combobox works fine.

**Comment by cody271** [comment]
> I'm on the latest. Here's a minimal example reproducing the issue:
>
Here is what I get from running your example:

<img width="308" alt="combo1" src="https://github.com/libui-ng/libui-ng/assets/11763424/d90cb283-193a-492e-8681-83d846dfbf2a">

<img width="311" alt="combo2" src="https://github.com/libui-ng/libui-ng/assets/11763424/6672d165-3824-4561-8cfd-c7315fb339d0">

This looks correct to me?

**Comment by desttinghim** [comment]
Hmm, I'm seeing something different. I'm on Windows 10, maybe that's the cause? The second and third pictures have the dropdown open, it's just very small.
![combobox](https://github.com/libui-ng/libui-ng/assets/10042482/ed2375d5-4335-441c-9b63-3ae9350b2645)
![combobox2](https://github.com/libui-ng/libui-ng/assets/10042482/dbb31c2b-e525-4550-860c-3e341bf593ef)
![combobox3](https://github.com/libui-ng/libui-ng/assets/10042482/9a25e30c-5340-45af-814b-1cf13ce0c238)

I am compiling this using zig, so that could also be the problem - actually, I just tested this, and running the examples compiled with meson does the right thing. Sorry for cluttering the issues!
