### ISSUE TITLE
"fonk" sound when using keyboard arrow keys

### ISSUE THREAD

**Issue by AndyObtiva** [libui-ng/libui-ng#204]
Hi,

I get a "fonk" sound whenever I use keyboard arrow keys in a Tetris game example I've built a while ago for [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui/issues/47):
https://github.com/AndyObtiva/glimmer-dsl-libui/blob/master/docs/examples/GLIMMER-DSL-LIBUI-ADVANCED-EXAMPLES.md#tetris

<img width="250" alt="Screenshot 2023-05-13 at 10 35 01 AM" src="https://github.com/libui-ng/libui-ng/assets/23052/f78f3eed-35b5-459b-a72c-92bcc46c562d">

I am basically capturing the key event (with a `on_key_down` shortcut syntax in Glimmer DSL for LibUI) and doing things based on which key is pressed:

```ruby
      on_key_down do |key_event|
        case key_event
        in ext_key: :down
          if OS.windows?
            # rate limit downs in Windows as they go too fast when key is held
            @queued_downs ||= 0
            if @queued_downs < 2
              @queued_downs += 1
              Glimmer::LibUI.timer(0.01, repeat: false) do
                @game.down! if @queued_downs < 2
                @queued_downs -= 1
              end
            end
          else
            @game.down!
          end
        in key: ' '
          @game.down!(instant: true)
        in ext_key: :up
          case @game.up_arrow_action
          when :instant_down
            @game.down!(instant: true)
          when :rotate_right
            @game.rotate!(:right)
          when :rotate_left
            @game.rotate!(:left)
          end
        in ext_key: :left
          @game.left!
        in ext_key: :right
          @game.right!
        in modifier: :shift
          @game.rotate!(:right)
        in modifier: :control
          @game.rotate!(:left)
        else
          # Do Nothing
        end
      end
```

Is there a way to have key events not produce that "fonk" sound?

This issue also just got reported to me by one of the user of Glimmer DSL for LibUI:
https://github.com/AndyObtiva/glimmer-dsl-libui/issues/47

**Comment by cody271** [comment]
> Is there a way to have key events not produce that "fonk" sound?
> 
This is actually the intended behavior for unhandled key events on Mac.

You have to acknowledge receipt of the key event as appropriate for that area control from within the callback.
`uiAreaHandler::KeyEvent` callback expects a return value for this purpose. Here is a simple patch to fix this:
```patch
diff --git a/lib/glimmer/libui/control_proxy/area_proxy.rb b/lib/glimmer/libui/control_proxy/area_proxy.rb
index 73f55bd..7c976be 100644
--- a/lib/glimmer/libui/control_proxy/area_proxy.rb
+++ b/lib/glimmer/libui/control_proxy/area_proxy.rb
@@ -179,7 +179,7 @@ module Glimmer
             @area_handler.DragBroken   = fiddle_closure_block_caller(0, [1, 1]) do |_, _|
               notify_custom_listeners('on_drag_broken')
             end
-            @area_handler.KeyEvent     = fiddle_closure_block_caller(0, [1, 1, 1]) do |_, _, area_key_event|
+            @area_handler.KeyEvent     = fiddle_closure_block_caller(1, [1, 1, 1]) do |_, _, area_key_event|
               area_key_event = ::LibUI::FFI::AreaKeyEvent.new(area_key_event)
               area_key_event = area_key_event_hash(area_key_event)
               notify_custom_listeners('on_key_event', area_key_event)
@@ -188,6 +188,7 @@ module Glimmer
               else
                 notify_custom_listeners('on_key_down', area_key_event)
               end
+              1
             end
             @listeners_installed = true
           end
```

**Comment by cody271** [comment]
We're still missing `uiArea` content in the new C docs, but this is explained in the old Go docs:
https://pkg.go.dev/github.com/libui-ng/golang-ui#AreaHandler

**Comment by AndyObtiva** [comment]
Wow! You're genius! I wasn't expecting you to fix Ruby code. Thank you for doing so! I am closing this issue as it is resolved.
