### ISSUE TITLE
Question: What is the role of `uiInitOptions`?

### ISSUE THREAD

**Issue by kojix2** [libui-ng/libui-ng#208]
Hi!
Thank you for maintaining libui-ng project. I have a question today.

In the header file `ui.h`, there is a defined structure called `uiInitOptions`. The pointer to `uiInitOptions` is used as an argument in the `uiInit` function.

```c
typedef struct uiInitOptions uiInitOptions;

struct uiInitOptions {
    size_t Size;
};

_UI_EXTERN const char *uiInit(uiInitOptions *options);
```

In addition, in `uipriv.h`, there is the following statement:

```c
// OS-specific init.* or main.* files
extern uiInitOptions uiprivOptions;
```

However, I'm not quite sure about the role of the `uiInitOptions` structure. Looking at the implementation of the `uiInit` function, regardless of whether it's Unix, macOS, or Windows:

```c
uiprivOptions = *o;
```

I don't know where it is being used. Is this a remnant of past implementations or a reserved value for future changes? 

Since I don't have a good understanding of C language, it's possible that this value is actually being used somewhere and I may have overlooked it. I would appreciate it if you could tell me how to use uiInitOptions correctly.

Thank you.

**Comment by cody271** [comment]
> I don't know where it is being used. Is this a remnant of past implementations or a reserved value for future changes?
> 
> Since I don't have a good understanding of C language, it's possible that this value is actually being used somewhere and I may have overlooked it. I would appreciate it if you could tell me how to use uiInitOptions correctly.

`uiInitOptions` was never actually used in the original lib, but we're keeping it for future use yes.
As long as the pointer is valid for the `uiInit()` call, it should be fine. Unlikely to be a GC issue.

**Comment by kojix2** [comment]
Thank you for your reply. Now I can make the change with peace of mind. Keep up the good work.

**Comment by kojix2** [comment]
https://github.com/libui-ng/libui-ng/pull/308
