### ISSUE TITLE
Property List control

### ISSUE THREAD

**Issue by AndyObtiva** [libui-ng/libui-ng#213]
I just received an interesting inquiry about LibUI by Twitter:
https://twitter.com/fum1h1ro/status/1675671247160745984?s=46&t=ya-5GNaRn-fWGJwN7Dgc0w

> “what I wanted to achieve was a PropertyList. The table can only contain the same type of controls in all rows, right? Therefore, I wanted to enumerate the items without using a table.”

Someone is trying to create a table that would have different types for different rows. That’s because they don’t want a standard table. What they really want is what is known as a Property List (used for configuration in Windows and Max apps). A property list usually has two columns with the first column serving as the header and the second one storing values in different types depending on the data. It’s sort of like a transposed table. 

Example of a property list:

https://www.codeproject.com/Articles/7282/Property-list-ActiveX-control

![IMG_6465](https://github.com/libui-ng/libui-ng/assets/23052/cacbc093-9f2f-4025-86d5-88223c23a938)

I believe Eclipse SWT already supports the ability to create a Property List with its Table widget because it offers support for arbitrary cell content, thus any table cell could have any arbitrary data type or data editors (e.g. drop-down, calendar, text entry, etc…)

It would be great if LibUI could eventually support a Property List control either:
- by providing similar support to LibUI table, but transposed, treating rows as columns and columns as rows, with the first column being the header
- by supporting arbitrary data content in table cells. 

It depends on which solution is most effective, cheapest, and/or best as a first step in an incremental multi step delivery of the feature.

**Comment by cody271** [comment]
> I just received an interesting inquiry about LibUI by Twitter: https://twitter.com/fum1h1ro/status/1675671247160745984?s=46&t=ya-5GNaRn-fWGJwN7Dgc0w
> 
Please copy the entire bug report here, or have the user report it to us directly. I can't view content behind a login wall.

> It depends on which solution is most effective, cheapest, and/or best as a first step in an incremental multi step delivery of the feature.

This is not how tables work.. Completely rewriting `uiTable` is not tenable / realistic.

Why not just use existing layout (either grid or even nested boxes) containers to arrange header and content "columns"?

**Comment by AndyObtiva** [comment]
I just updated the issue by adding the tweet body (it was in reaction to using LibUI through Glimmer DSL for LibUI in Ruby by the way). 

> This is not how tables work.. Completely rewriting uiTable is not tenable / realistic.

SWT’s cross-platform table does work that way though by allowing insertion of anything into any cell as far as I know. I believe Java Swing’s table supports that as well, so it’s not uncommon. 

Also, I didn’t ask for rewriting the table control completely. It would be nice to keep all the existing simple table features it offers, but then add more flexibility on top of that for when it’s needed. This follows the 80/20 rule of providing a simple way to use a table 80% of the time, but then in the rare exceptional 20% of the time, more flexibility is offered by allowing any cells to contain any type of data or data editors

> Why not just use existing layout (either grid or even nested boxes) containers to arrange header and content "columns"?

Thank you for the suggestion. That could be a useful workaround for now. I will relay it to the tweet author. 

However, some software engineers might want the PropertyList to look like a table just like the PropertyList table ActiveX control I shared a link of. And, I would imagine that supporting arbitrary types of data in any table cells is a more common use case than originally thought, so it wouldn’t hurt to support it eventually while keeping the quick and simple support for the most common table use cases too. 

That said, I did mention the transposed table alternative as a much simpler option to support first. If supported, it could be activated by passing one option to table while the rest is the same (e.g. pass transposed as true or some other name for the option).

**Comment by cody271** [comment]
> However, some software engineers might want the PropertyList to look like a table just like the PropertyList table ActiveX control I shared a link of.
>
This "property list" control is a custom self drawn ActiveX based control. Very Windows specific, not even part of Win32 common controls! And has no equivalent control available on Darwin or Unix.. So I don't see how we would actually implement this?

**Comment by cody271** [comment]
> And, I would imagine that supporting arbitrary types of data in any table cells is a more common use case than originally thought
> 
> That said, I did mention the transposed table alternative as a much simpler option to support first.

Again, neither of these suggestions are compatible with how table API works currently. See `uiTableModelHandler`.

**Comment by szanni** [comment]
I don't believe the property list should in _any_ way be intermingled with `uiTable`.
Yes, it looks like a table because of the grid, but what you are semantically looking for is clearly a form. And we already have controls for creating those, sans the visual grid lines and with slightly differing alignment. `uiGroup` and `uiForm` are your friends here (from `controlgallery`):

![image](https://github.com/libui-ng/libui-ng/assets/286606/b322105d-828c-449a-9b3a-46cfa57265cb)

So if anything look into implementing a `uiFormSetLabelAlignment(uiForm*, uiAlign)` that accepts both `uiAlignStart` and `uiAlignEnd`.

**Comment by cody271** [comment]
> So if anything look into implementing a `uiFormSetLabelAlignment(uiForm*, uiAlign)` that accepts both `uiAlignStart` and `uiAlignEnd`.

First attempt at this more actionable feature request, does this work instead?

![image](https://github.com/libui-ng/libui-ng/assets/11763424/aa4fe5ed-28e0-43d8-b165-e90c01968063)

**Comment by AndyObtiva** [comment]
> @AndyObtiva : Thank you for the suggestion. That could be a useful workaround for now. I will relay it to the tweet author.

Actually, as per my last reply, I did relay the form solution to the issue reporter:
https://twitter.com/AndyObtiva/status/1675941772113899532?s=20

> When I explained the idea of a PropertyList to the maintainer of the LibUI project, he shared his opinion that it is not a common use of a table, and that it’s better to implement as simply a form with labels on the left side and fields on the right side (entry, combobox, etc…).

He replied with acceptance and thanks:
https://twitter.com/fum1h1ro/status/1676021918103896064?s=20

> Oh...I see. Well, PropertyList is special. It's a closed tool, so it's ok. Thanks for your consideration!

Thank you for providing your opinions and input about this. I would personally use the same solution you suggested for this problem instead of repurposing a table for editing non-tabular data.

I am closing this issue.
