### ISSUE TITLE
Documentation: what's the difference between uiFreeControl and uiControlDestroy

### ISSUE THREAD

**Issue by teras** [libui-ng/libui-ng#221]
Hello and thank you for this awesome library!

In order to have proper memory management, what's the difference between uiFreeControl and uiControlDestroy? When to use the first and when the second?

To my understanding, it's confusing if we should use both, or only one, and under which conditions.

**Comment by cody271** [comment]
> what's the difference between uiFreeControl and uiControlDestroy? When to use the first and when the second?
>

`uiControlDestroy()` calls the platform specific APIs that actually destroy a control (and its children), `uiFreeControl()` just frees the memory associated with the control reference. `uiFreeControl()` is only public for writing custom controls.

Most of the time, you should only need to use `uiControlDestroy()` directly, and only on your main top level window.

**Comment by teras** [comment]
Thank you for the clarification. If you don't mind I'll prepare a PR stating what you said, for future documentation.
