### ISSUE TITLE
Unnecessary auto scrolling with uiEntrySetText on Windows

### ISSUE THREAD

**Issue by matyalatte** [libui-ng/libui-ng#232]
I want to set default vaules to `uiEntry`.
But when you use `uiEntrySetText` at launch, the app scrolls the edit control horizontally even if it has enough width to show whole text.

As an example, I set a to z as a default value in the control gallery on Windows 10.
```c
uiEntry* e = uiNewEntry();
uiEntrySetText(e, "abcdefghijklmnopqrstuvwxyz");
uiFormAppend(entryForm,
  "Entry",
  uiControl(e),
  0);
```

Then, it showed from m at launching.
![unexpected](https://github.com/libui-ng/libui-ng/assets/69258547/68e1035c-2d1b-4ec2-882d-25f20b76d726)

What I expected was like this.
![expected](https://github.com/libui-ng/libui-ng/assets/69258547/e7490ddc-1c84-441a-9e1a-641e822e7320)

Is there any workaround for it?
I noticed you can pass the default value to `uiWindowsEnsureCreateControlHWND` to fix.
But it requires a new function like `uiNewEntryWithParams`...

**Comment by szanni** [comment]
> But when you use `uiEntrySetText` at launch, the app scrolls the edit control horizontally even if it has enough width to show whole text.

Thanks for the report.
Confirmed. Both on Windows 7 and wine 8.16.

You can see for yourself using the `qa > uiEntry > 4. Entry Long Text` [here](https://github.com/szanni/libui-ng/tree/bug-windows-entry-long-text-scroll) (which we should commit to master once fixed).

My hunch tells me it has got to do with the cursor position introduced in  81b294181c839e8e87c0a7f4e02da652ed027b8b

> I noticed you can pass the default value to `uiWindowsEnsureCreateControlHWND` to fix.

Could you elaborate/share the code snippet?

**Comment by matyalatte** [comment]
Thanks for the reply.

> Could you elaborate/share the code snippet?

You can set a default value with `finishNewEntry` like this.

```c++
static uiEntry *finishNewEntry(DWORD style, const char* text)
{
  ⋮
  WCHAR *wtext = toUTF16(text);
  e->hwnd = uiWindowsEnsureCreateControlHWND(WS_EX_CLIENTEDGE,
      L"edit", wtext,
      style | ES_AUTOHSCROLL | ES_LEFT | ES_NOHIDESEL | WS_TABSTOP,
      hInstance, NULL,
      TRUE);
  uiprivFree(wtext);
  ⋮
```

But it only works when creating the control.
It would be great if `uiEntrySetText` works fine.

**Comment by szanni** [comment]
> You can set a default value with `finishNewEntry` like this.

I understand, setting the text upon creation. As you noticed yourself that is not really a solution for the `uiEntrySetText` call in general.

Offending line is definitely `windows/entry.cpp:71` introduced in #102: ` Edit_SetSel(e->hwnd, l, l);`.
If I comment that line out things display correctly on my system.
But then it messes with the cursor being at the beginning of the line when the `uiEntry` is already focused and `uiEntrySetText` is called.

Note: The weird display behavior only happens upon window creation and not subsequent calls to `uiEntrySetText` when the application is already running (and win32 having the actual `uiEntry` dimensions?).

Maybe we can only set the cursor position if the control is already focused? I am unclear on what the use case of #102 was in the first place... on my system cursor position is wherever I click on the control when the control is not already focused. Was this solely  for cursor placement when focused?
