### ISSUE TITLE
Tab selection events

### ISSUE THREAD

**Issue by AndyObtiva** [libui-ng/libui-ng#253]
Hi,

In the current LibUI API, I did not find any way to listen to the event of when a user selected a certain tab to see its content. 

It would be great to have that functionality as it would enable things like:
- Tracking which tab the user has selected to perform certain actions when the tab content is displayed, like remembering tab browsing history or refreshing data.
- Delaying the population of tab content until a tab is selected, which can optimize the startup time of certain apps.

For an example of such an implementation, Eclipse SWT `TabFolder` supports tracking tab selection with the `addSelectionListener` method:
https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/widgets/TabFolder.html

I use that functionality in [Gladiator (Glimmer Editor)](https://github.com/AndyObtiva/glimmer-cs-gladiator) to save a history of user tab selection actions to remember which files the user viewed last.

It would be great if I could have that same functionality in LibUI. Initially, the "tab selected event" could be sufficient. Eventually, the "tab unselected event" might be useful too (like for performing cleaning of resources).

**Comment by AndyObtiva** [comment]
Has there been any progress on this issue? I just created a syntax highlighting editor using the libui area control, and I would like to embed in a multi-tab code editor application that allows opening and closing tabs.

![glimmer-dsl-libui-code-editor](https://github.com/user-attachments/assets/02f1c990-7155-49e0-af33-5cb5e906c3d8)

Even if I do not get the uiTabOnSelected event, at least having a general uiControlOnFocused or controlOnVisible event could help solve this problem of allowing users to close visible tab items.

**Comment by petabyt** [comment]
I think this is a good feature, here's some notes:

- GTK3: Switch-page: https://docs.gtk.org/gtk3/signal.Notebook.switch-page.html
- Cocoa: MyTabViewDelegate tabView:willSelectTabViewItem: or tabView:didSelectTabViewItem:
- win32: Tab change event is already handled: https://github.com/libui-ng/libui-ng/blob/49b04c4cf8ae4d3e38e389f446ef75170eb62762/windows/tab.cpp#L81

>  I just created a syntax highlighting code editor using the libui area control

Very impressive by the way :)

**Comment by cody271** [comment]
@AndyObtiva Tab selection has been fixed in #289.
