### ISSUE TITLE
Can libui be used with a window/app created with SDL, GLFW, or similar toolkits?

### ISSUE THREAD

**Issue by cblc** [libui-ng/libui-ng#283]
If the question has a positive answer, it could probably fix https://github.com/libui-ng/libui-ng/issues/79

The idea would be that you use SDL2, GLFW, or a similar toolkit, for creating graphics windows, while libui would be used just for the menu and for dialogs (ie, no controls created on the graphics window, just on dialogs and on the menu bar).

Would it be necessary to patch SDL2/GLFW/etc for getting the (platform-dependent) graphics window pointer, or the app pointer? Or it wouldn't be necessary?

IMHO, this would be a great way of having graphics windows together with a libui gui. Graphics toolkits are complex enough, support many backends (Metal, Vulkan, OpenGL, etc), and I believe it makes sense to use them rather than to implement support for graphics windows in libui-ng.

**Comment by ethindp** [comment]
For SDL2, this is trivially resolved, I think, by the [SDL_GetWindowWMInfo](https://wiki.libsdl.org/SDL2/SDL_GetWindowWMInfo) function.

**Comment by rubyFeedback** [comment]
> IMHO, this would be a great way of having graphics windows together with a libui gui. Graphics toolkits are complex enough, support many backends

I agree. Note that libui-ng fork was mostly done for solving already provided patches to libui, which was (more or less) abandoned. So I think we have to expect a slow pace for libui-ng, as it is not a full time job for any dev. Best results for addition of code I saw through pull requests by people, and cody reviewing these. (There have been comments to make code changes easier; I am not one of the core devs, so I do not know how this went; I am mostly just focusing on ruby stuff in general. C and C++ is for the really clever people.)

**Comment by cody271** [comment]
> Can libui be used with a window/app created with SDL, GLFW, or similar toolkits?
>
Yes, a hybrid libui + SDL application certainly *is* possible..
Here is a GTK + SDL hybrid demo app for an example: https://github.com/AlejandroIbarraC/GTK-SDL2

> If the question has a positive answer, it could probably fix https://github.com/libui-ng/libui-ng/issues/79
>
Unfortunately no, doesn't really help much: the hard work is still providing a consistent 3D *rendering* API across all platforms. 3D graphics windows integration with each native platform is trivial in comparison. SDL/GLFW aren't high level game engines. See my previous comment in that issue: https://github.com/libui-ng/libui-ng/issues/79#issuecomment-1535683340
