### ISSUE TITLE
Add proper copyright attribution.

### ISSUE THREAD

**Issue by szanni** [libui-ng/libui-ng#38]
I think we need a way of properly assigning copyright, similar to how other open source projects handle this.

I would suggest either an AUTHORS file or IMO even better: listing contributors at the bottom of the LICENSE file.

The copyright in the LICENSE file has already been changed to `Copyright (c) 2022 libui-ng authors`.
How about adding a list of authors at the bottom of said file?
```
Copyright (c) 2022 libui-ng authors
....

Authors
=======

First Last
```

Somebody would have to go through the git log and add the names.
New contributors would add their name themselves (remark in CONTRIBUTING.md needed).

**Comment by cody271** [comment]
> 
> Somebody would have to go through the git log and add the names. New contributors would add their name themselves (remark in CONTRIBUTING.md needed).
>
I've opened a PR with an `AUTHORS.md` file [here](https://github.com/libui-ng/libui-ng/pull/39), automatically generated from the git history and sorted by number of contributions. Please everyone review and confirm that your entry in the file is correct before I merge.

**Comment by rubyFeedback** [comment]
While I am not against the suggestion, there are some people who don't care - see projects such as the "unlicence" or whatever the name was. I also just use a nick to provide feedback (which, hopefully, is SOMETIMES useful). All my contributions in general are always "no need to give me credit" and I literally mean that too. (This may be a bit different with a few of my own personal projects I maintain on my own, but when I contribute anything to other projects I literally don't care about getting any credit for it. So my comment here is mostly to also account for people who really don't even need or want to be listed in authors. For those who do, that's ok of course.)

I think "libui-ng authors" is a good summary, and people who want to be listed in AUTHORS.md can say so. IMO I think to many people it is much more important that the spirit of libui is kept alive than bother with "due credit". :D

**Comment by szanni** [comment]
I fully agree that some authors do not care. That sadly does not mean the law does not!
You even listed "unlicense" as an example. Why does it exist in the first place? Because there are countries where you can not sign things into the public domain. Germany is one such example.

> IMO I think to many people it is much more important that the spirit of libui is kept alive than bother with "due credit". :D
I truly hope so. I do hope this is true for all contributors as well. But who knows?

I am especially concerned with people using the software in commercial, closed source projects. Having a proper way of assigning copyright and attribution will give such projects peace of mind. There have been countless cases of people suing for all sorts of supposed license infringement.

**Comment by cody271** [comment]
> I fully agree that some authors do not care. That sadly does not mean the law does not!
> 
Exactly. We have to care. 💯
Users must be free to use libui-ng in both free and proprietary software without legal concerns!
This project isn't very relevant or useful if it is legally encumbered..

**Comment by cody271** [comment]
> The copyright in the LICENSE file has already been changed to Copyright (c) 2022 libui-ng authors.
> How about adding a list of authors at the bottom of said file?
>
I intentionally did not do this, because it is much riskier to have frequent edits to the license file versus an authors file. This is why many projects use `Copyright The Project Authors` in their licenses like I've done here. This has become even more important in recent years, as automated tools now scan the license files for compliance. Notice how GitHub knows that libui-ng is MIT licensed, and shows that information clearly.. but doesn't recognize the same license for original libui, because the license file had [minor edits](https://github.com/libui-ng/libui-ng/commit/16d8bfd9ae17537dcaae8518e41428acdc32ced3#diff-4673a3aba01813b595de187a7a6e9e63a3491d55821606fecd9f13a10c188a1d).

**Comment by cody271** [comment]
Thinking more long term.. at some point, if this project gets large enough, we'll probably want to adopt a DCO policy. No CLAs ever, of any kind.

**Comment by szanni** [comment]
> > The copyright in the LICENSE file has already been changed to Copyright (c) 2022 libui-ng authors.
> > How about adding a list of authors at the bottom of said file?
> 
> I intentionally did not do this, because it is much riskier to have frequent edits to the license file versus an authors file. This is why many projects use `Copyright The Project Authors` in their licenses like I've done here. This has become even more important in recent years, as automated tools now scan the license files for compliance. Notice how GitHub knows that libui-ng is MIT licensed, and shows that information clearly.. but doesn't recognize the same license for original libui, because the license file had [minor edits](https://github.com/libui-ng/libui-ng/commit/16d8bfd9ae17537dcaae8518e41428acdc32ced3#diff-4673a3aba01813b595de187a7a6e9e63a3491d55821606fecd9f13a10c188a1d).

Oh wow. Good to know. I had no idea. I guess there is a reason why projects to place authors in a separate file. I was more thinking of package maintainers, where having everything in one file makes things marginally easier.

> Exactly. We have to care. 💯 Users must be free to use libui-ng in both free and proprietary software without legal concerns! This project isn't very relevant or useful if it is legally encumbered..

This is exactly the reason I opened this ticket. Thanks for communicating this more clearly.
