### ISSUE TITLE
uiLoadControlFont

### ISSUE THREAD

**Issue by cody271** [libui-ng/libui-ng#4]
Default font API, https://github.com/andlabs/libui/pull/388

**Comment by cody271** [comment]
Nit: need to also add `uiFreeFontDescriptor()` now, after merge.

**Comment by cody271** [comment]
@inkydragon Almost forgot: When you got a chance, can you please test the `drawtext` example  on Windows and confirm that the `System Font` checkbox now works as expected? Thanks

**Comment by inkydragon** [comment]
@cody271 It seems to work.
![image](https://user-images.githubusercontent.com/5158738/148753646-8af76305-4cb6-42dc-90fc-d79afc869726.png)
![image](https://user-images.githubusercontent.com/5158738/148753616-273dce49-22fe-4107-aaaa-1de654196d2c.png)

**Comment by cody271** [comment]
Looks good. We have the first old PR merged, and confirmed working!
