### ISSUE TITLE
Use Doxygen to output XML 

### ISSUE THREAD

**Issue by simplexidev** [libui-ng/libui-ng#63]
This should allow for language bindings to be generated based on the XML file.

This, as per [Doxygen's documentation](https://www.doxygen.nl/manual/config.html#cfg_generate_xml), the XML file produced "*captures the structure of the code including all documentation.*"

**Comment by rubyFeedback** [comment]
How difficult would it be to enable doxygen? (Rationale for my question: trying to keep the workload for cody as low as possible. The original libui was most active from ~early 2015 to late 2019 or something like that, so hopefully libui-ng can fix a ton of things before it also becomes less active again :D )

**Comment by simplexidev** [comment]
I don't know much about it at all, honestly. It was just a thought, as an XML file defining the external methods, structs, and enums would make it easy to generate C# bindings. 

But I would assume not too difficult, based on the link above. That's about all I could find though.

**Comment by cody271** [comment]
> This should allow for language bindings to be generated based on the XML file.
> 
Indeed, the original bindings generator prototype actually used the XML output of [`cldoc`](https://github.com/andlabs/libui/pull/175).
You can see the results of that experiment in the [Lua bindings](https://github.com/cody271/luajit-libui) which were generated this way.

The new bindings generator will use libclang directly to parse `ui.h`.

**Comment by szanni** [comment]
Although this is closed a warning to anyone who finds this thread and would like to attempt something like this:
Make sure the Doxygen XML output is complete/contains the bits and pieces you need. The C back end is in a very dire state and the XML output very incomplete. I sadly stumbled across this when submitting patches for C constructor and destructor annotations.
