### ISSUE TITLE
Can we have uiSliderOnReleased?

### ISSUE THREAD

**Issue by MikeWang000000** [libui-ng/libui-ng#89]
Is it possible to add function uiSliderOnReleased?
In Qt, I can use `SIGNAL(sliderReleased())` to detect when user finishes dragging the slider.
Thanks!

**Comment by mohad12211** [comment]
This can be achieved with `g_signal_connect(s->scale, "button-release-event", G_CALLBACK(onReleased), s);` in slider.c for unix. idk about other platforms.

**Comment by MikeWang000000** [comment]
It's not easy to do this directly in libui-ng at the moment. If necessary, I'll try to make a pr adding this api when I have time?

**Comment by mohad12211** [comment]
I did the unix and darwin api for now, I have no idea on how to make the windows one. if you can work on that, it would be nice.

**Comment by MikeWang000000** [comment]
haha thank you！I just did't know how to deal with it in Linux。The Windows one is done now。

**Comment by cody271** [comment]
> haha thank you！I just did't know how to deal with it in Linux。The Windows one is done now。

Thanks @MikeWang000000, we need more Windows developers!

**Comment by cody271** [comment]
Fixed in #91
